//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 金证统一账户测试账户生成器.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://60.173.222.38:30004/kess/services/KessService?wsdl")]
        public string webservice {
            get {
                return ((string)(this["webservice"]));
            }
            set {
                this["webservice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90019")]
        public string 操作员代码 {
            get {
                return ((string)(this["操作员代码"]));
            }
            set {
                this["操作员代码"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("888888")]
        public string 操作员密码 {
            get {
                return ((string)(this["操作员密码"]));
            }
            set {
                this["操作员密码"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string 操作渠道 {
            get {
                return ((string)(this["操作渠道"]));
            }
            set {
                this["操作渠道"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int 中登超时时间 {
            get {
                return ((int)(this["中登超时时间"]));
            }
            set {
                this["中登超时时间"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public string 开户营业部 {
            get {
                return ((string)(this["开户营业部"]));
            }
            set {
                this["开户营业部"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20")]
        public string Cols {
            get {
                return ((string)(this["Cols"]));
            }
            set {
                this["Cols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5|5|4|1|4|1|1|1|1|5|1|1|1|1|1|5|5|3|1|5")]
        public string 保守型 {
            get {
                return ((string)(this["保守型"]));
            }
            set {
                this["保守型"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5|5|1|1|4|1|1|1|1|5|1|1|1|1|1|1|1|3|3|5")]
        public string 谨慎型 {
            get {
                return ((string)(this["谨慎型"]));
            }
            set {
                this["谨慎型"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2|2|2|2|2|2|2|2|2|2|2|2|2|2|2|2|3|2|2|2")]
        public string 稳健型 {
            get {
                return ((string)(this["稳健型"]));
            }
            set {
                this["稳健型"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2|2|1|2|1|3|3|4|2|4|3|5|4|4|4|1|1|1|3|4")]
        public string 积极型 {
            get {
                return ((string)(this["积极型"]));
            }
            set {
                this["积极型"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1|5|1|2|3|4|3|2|5|3|3|4|4|4|3|1|1|1|3|1")]
        public string 激进型 {
            get {
                return ((string)(this["激进型"]));
            }
            set {
                this["激进型"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SURVEY_SN {
            get {
                return ((string)(this["SURVEY_SN"]));
            }
            set {
                this["SURVEY_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("028a")]
        public string 默认开通的操作渠道 {
            get {
                return ((string)(this["默认开通的操作渠道"]));
            }
            set {
                this["默认开通的操作渠道"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("z")]
        public string 默认开通的资产账户类别 {
            get {
                return ((string)(this["默认开通的资产账户类别"]));
            }
            set {
                this["默认开通的资产账户类别"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5200")]
        public string 默认开通的银行类型 {
            get {
                return ((string)(this["默认开通的银行类型"]));
            }
            set {
                this["默认开通的银行类型"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0")]
        public string 风险测评版本号 {
            get {
                return ((string)(this["风险测评版本号"]));
            }
            set {
                this["风险测评版本号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U")]
        public string 统一账户版本 {
            get {
                return ((string)(this["统一账户版本"]));
            }
            set {
                this["统一账户版本"] = value;
            }
        }
    }
}
